# Site settings
title: Indico Project
email: indico-team@cern.ch
description: > # this means to ignore newlines until "baseurl:"
 Indico Project Official site - Indico is a powerful event (meetings, conferences, lectures)
 management system developed at CERN
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://getindico.io" # the base hostname & protocol for your site
twitter_username: getindico
github_username: indico
disqus_shortname: indico-project

gems:
  - jekyll-feed

# Build settings
markdown: kramdown
